---
- name: Install Courier IMAP daemon
  apt: pkg=courier-imap state=present
  register: courierimapinstalled

- name: Install Courier IMAP configuration
  template: owner=root group=root
    src=imapd.tmpl
    dest=/etc/courier/imapd
  notify: Restart courier imap

