---
- name: Install Courier IMAP daemon
  apt: pkg=courier-imap state=present
  register: courierimapinstalled

- name: Install Courier IMAP configuration
  template: owner=root group=root
    src=imapd.tmpl
    dest=/etc/courier/imapd
  notify: Restart courier imap

- name: Create directory for shared index
  when: filesystems_ro_rootfs_enable
  file: owner=daemon group=daemon mode=755
    state=directory
    path=/var/cache/courier/shared/

