---
- include: install-courier-imap.yml tags=system,mail,courier,imap
  when: courier_imap_enable

- include: install-courier-imap-ssl.yml tags=system,mail,courier,imap,ssl
  when: courier_imap_ssl_enable

- include: install-courier-esmtpd.yml tags=system,mail,courier,smtp
  when: courier_esmtpd_enable

- include: install-courier-esmtpd-ssl.yml tags=system,mail,courier,smtp,ssl
  when: courier_esmtpd_ssl_enable

